transcriptome: path/to/transcriptome.fasta
output_dir: TheOutputDirPath
basename: basename
memory: 12 # memory in GB, might change later
threads: 8 # logic threads, not physical cores, for clarity
R1: path/to/reads/R1.fastq
R2: path/to/reads/R2.fastq # if paired-end reads
contaminants: 
proteome_fasta: #path/to/proteome.faa # if run in proteome mode
toxin_db: path/to/Toxines-DB.fa
pfam_db_path: 
swissprot_db_path: 
toxins_evalue: "1e-10"
contamination_evalue: "1e-5"
clustering_threshold: "0.99"
maxlen: 45000
signalp_dvalue: "0.7"
wolfPsort_path: ~/WoLFPSort/bin/runWolfPsortSummary
quant: True
TPMthreshold: "1000"
wolfpsort: False
swissprot: True
swissprot_evalue: "1e-10"
cys_pattern: True