transcriptome: test/transcriptome.fasta
basename: basename
memory: 12 # memory in GB, might change later
threads: 8 # logic threads, not physical cores, for clarity
R1: test/R1.fastq.gz
R2: test/R2.fastq.gz
adapters: test/adapters.fasta
contaminants: test/contaminants.fasta 
contamination_evalue: "1e-5"
clustering_threshold: "0.9"
maxlen: 450
signalp_path: ~/signalp-5.0b/bin/